# TD 1 | Introduction à Python pour l'analyse de données

---

Objectifs du TD :

* découvrir Python
* se familiariser avec le langage et le notebook Jupyter
* découvrir et maîtriser les bases des librairies de calcul numérique et d'analyse de données numpy et pandas

---

##  Installation de Python et Jupyter

### Windows

#### Installation Python

Vérifiez si vous avez déjà une version de python installée en ouvrant l'invite de commande et en exécutant l'une des deux commandes python suivantes : 
> python --version   

> python3 --version 

Si ce n'est pas le cas, vous pouvez procéder à l'installation comme suit :
 
1. Allez sur le site web : https://www.python.org/downloads/windows/
2. Cliquez sur "Latest Python 3 Release - Python 3.10.7".
3. Si votre ordinateur utilise une version 64 bits de Windows, téléchargez le Windows installer (64-bit). Sinon, téléchargez Windows installer (32-bit).
4. Après avoir téléchargé le Windows installer, vous devez l'exécuter (double-cliquez dessus) et suivre les instructions qui s'y trouvent.

NB : Au début de l'installation, assurez-vous de cocher la case "Add Python 3.10 to PATH" ou "Add Python to your environment variables" avant de cliquer sur "Install Now".


#### Installation Jupyter

Ouvrir l'invite de commande et exécuter la commande suivante en remplaçant Pseudo_de_votre_user par le nom de l'utilisateur de votre session : 
> cd "C:\Users\Pseudo_de_votre_user\AppData\Local\Programs\Python\Python310\Scripts"

Ensuite, executer la commande suivante :
> pip install jupyterlab

Une fois l'installation terminée avec succès, vous pouvez lancer JupyterLab avec la commande suivante : 
> jupyter-lab


### Linux & Mac OS

#### Installation Python

Normalement, Python est préinstallé sur la quasi-totalité des distributions. Vous n'avez pas besoin de le réinstaller, mais vous pouvez mettre à jour la version si vous le souhaitez.

Vérifiez la version Python installée en exécutant l'une des deux commandes python suivantes sur votre terminal : 
> python --version   

> python3 --version 

#### Installation Jupyter

Vérifier que la commande pip3 est installée. Sinon, l'installer (exemple pour Debian/Ubuntu/Linux Mint, à adapter selon votre distribution) :

> sudo apt install python3-pip

Ensuite, installer JupyterLab en executant la commande suivante:
> pip3 install -U jupyterlab

Enfin, placez-vous dans votre dossier de travail et lancez un notebook :

> jupyter-lab

## Syntaxe et Concepts de base

In [5]:
a = 33
b = 9
c = 2.0

In [6]:
a+b

42

In [7]:
print(a+b)

42


In [8]:
type(a)

int

In [9]:
type(c)

float

In [10]:
a = 'hello'
type(a)

str

In [11]:
# Affiche les entiers pairs de 1 à 10
for i in range(1, 11):
    if i % 2 == 0:
        print(i)

2
4
6
8
10


### List

In [12]:
l = [1,2,3,4,4]

#### len, max, min

In [13]:
print('longueur de la liste =', len(l))
print("Valeur max de l =", max(l))
print("Valeur min de l =", min(l))

longueur de la liste = 5
Valeur max de l = 4
Valeur min de l = 1


#### Ajout d'un élément d'une liste

In [14]:
l.append(6)
l

[1, 2, 3, 4, 4, 6]

In [15]:
l = l+[7]
l

[1, 2, 3, 4, 4, 6, 7]

In [16]:
l+=[7]
l

[1, 2, 3, 4, 4, 6, 7, 7]

#### Modifier un élément

In [17]:
l[0] = 29
l

[29, 2, 3, 4, 4, 6, 7, 7]

In [18]:
l.insert(1,9)
l

[29, 9, 2, 3, 4, 4, 6, 7, 7]

#### Suppression des éléments d'une liste

In [19]:
l.remove(7)
l

[29, 9, 2, 3, 4, 4, 6, 7]

In [20]:
l.pop(2)
l

[29, 9, 3, 4, 4, 6, 7]

#### Trier une liste

In [21]:
l.sort(reverse=True)
print(l)

[29, 9, 7, 6, 4, 4, 3]


In [22]:
l_sorted = sorted(l)
print('Sorted list:', l_sorted)

Sorted list: [3, 4, 4, 6, 7, 9, 29]


#### Liste non homogène

In [23]:
l = [1, 'un', 2]
l.append('deux')
l += [3, 'trois']
print(type(l))
l

<class 'list'>


[1, 'un', 2, 'deux', 3, 'trois']

In [24]:
a = l[3], l[-1]
print(type(a))
a

<class 'tuple'>


('deux', 'trois')

In [25]:
a[0]

'deux'

In [26]:
[2**p for p in range(10)] # "Compréhension de liste"

[1, 2, 4, 8, 16, 32, 64, 128, 256, 512]

In [27]:
# Liste des entiers pairs de 1 à 10
l = [i for i in range(1, 11) if i % 2 == 0]
print(l)

[2, 4, 6, 8, 10]


### Tuple

In [28]:
p = tuple(range(1,5))
print("p=", p)
print("p[0] = ", p[0])

p= (1, 2, 3, 4)
p[0] =  1


In [29]:
p = ([1,2],5)

print(p)

p[0][0] = 8

print(p)

([1, 2], 5)
([8, 2], 5)


In [30]:
# Les éléments du tuple sont fixes
#p[0] = 6

In [31]:
p1 = (1,2)
p2 = (2,1)

print(p1 == p2)

False


### Set

In [32]:
s = set((1,2,'l'))
print(s)

s = {4,5,9,9,9,9}
print(s)

{1, 2, 'l'}
{9, 4, 5}


In [33]:
#Ajout d'un élément au set
s.add(6)
print(s)

{9, 4, 5, 6}


In [34]:
#Suppression d'un élément du set
s.discard(5)
print(s)

{9, 4, 6}


In [35]:
s.clear()
print(s)

set()


In [36]:
A = {1,2,3,4,5}
B = {2,4,6,7}
C = {1,2,3}

In [37]:
#Intersection
print("Intersection de A et B =", A&B)

#Union
print("Union entre A et B =", A|B)

#Exclusion
print("Exclusion de B de A =", A-B)

#Différence symétrique
print("Diff sym. A et B =", A^B)

Intersection de A et B = {2, 4}
Union entre A et B = {1, 2, 3, 4, 5, 6, 7}
Exclusion de B de A = {1, 3, 5}
Diff sym. A et B = {1, 3, 5, 6, 7}


In [38]:
print("B est inclus strict dans A") if A>B else print(False)
print("C est inclus dans A") if A>=C else print(False)

False
C est inclus dans A


### Dictionary

In [39]:
# 1ère façon de créer un dictionnaire
dic = {"key1": "value1", "answer": 42}
# 2ème façon de créer un dictionnaire
dic2 = dict(key1="value1", answer=42)
# 3ème façon de créer un dictionnaire
dic3 = dict([("key1","value1"), ("answer",42)])
print(dic)
print(dic2)
print(dic3)

dic["answer"]

{'key1': 'value1', 'answer': 42}
{'key1': 'value1', 'answer': 42}
{'key1': 'value1', 'answer': 42}


42

In [40]:
dic['new'] = [1,2,3]

In [41]:
dic.keys()

dict_keys(['key1', 'answer', 'new'])

In [42]:
dic.items()

dict_items([('key1', 'value1'), ('answer', 42), ('new', [1, 2, 3])])

In [43]:
dic.values()

dict_values(['value1', 42, [1, 2, 3]])

In [44]:
a,b,c = dic.items()
print(a)

('key1', 'value1')


## Programmation Orientée Objet

In [45]:
"""
Exemple de classe en Python
"""
class Moteur:
    
    # Constructeur
    def __init__(self, esn, panne=False):
        self.esn = esn
        self.panne = panne
    
    # Méthodes
    def dire_bonjour(self):
        print('Bonjour, mon numéro de série est ' + self.esn)
    
    def fonctionne(self):
        return not self.panne 
    

In [46]:
mot1 = Moteur('420912')
mot2 = Moteur(panne=True, esn='420913')

mot1.dire_bonjour()
print(mot1.fonctionne())

mot1.panne = True
print(mot1.fonctionne())

print('\n')
mot2.dire_bonjour()
print(mot2.fonctionne())

Bonjour, mon numéro de série est 420912
True
False


Bonjour, mon numéro de série est 420913
False


### Méthode récurcive vs Méthode itérative

In [47]:
# Méthode récursive
def fact1(n):
    if n == 0:
        return 1
    else:
        return n*fact1(n-1)

# Méthode itérative
def fact2(n):
    s=1
    for i in range(1,n+1):
        s*=i
    return s

print(fact1(5))
print(fact2(5))

120
120


In [48]:
"""
App.1 : Ecrire une fonction qui retourne le plus grand commun diviseur (pgcd) entre deux nombres a et b.
"""

'\nApp.1 : Ecrire une fonction qui retourne le plus grand commun diviseur (pgcd) entre deux nombres a et b.\n'

In [49]:
import math as ma


def pgcd_it(a, b):
    M =max(a,b)
    for i in range(1,int(ma.sqrt(M))+ 1):
        if a % i == 0 and b % i == 0:
            res = i
    return res


def pgcd_rec(a, b):
    if a == 0 or b == 0 :
        return (a+b)
    else:
        r=a%b
        return pgcd_rec(b,r)

a=230
b=25
print("pgcd_it(a,b) = ", pgcd_it(a,b))
print("pgcd_rec(a,b) = ", pgcd_rec(a,b))



pgcd_it(a,b) =  5
pgcd_rec(a,b) =  5


In [50]:
"""
App.1 : Correction
"""

#Méthode itérative
def pgcd1(a,b):
    while (a%b) != 0:
        s = a%b
        a = b
        b = s
    return b


#Méthode récurcive
def pgcd2(a,b):
    if a==b : return a 
    if a<b : a,b = b,a
    return pgcd2(a-b,b)

a = 230
b = 25

print("pgcd1(a,b) = ", pgcd1(a,b))
print("pgcd2(a,b) = ", pgcd2(a,b))

pgcd1(a,b) =  5
pgcd2(a,b) =  5


## Libraries

> pip install numpy pandas

> pip3 install -U numpy pandas

### Math

In [51]:
import math

In [52]:
x = 4

print("sqrt(x) =", math.sqrt(x))
print("cos(x) =", math.cos(x))
print("sin(x) =", math.sin(x))
print("factorial(x) =", math.factorial(x))

sqrt(x) = 2.0
cos(x) = -0.6536436208636119
sin(x) = -0.7568024953079282
factorial(x) = 24


### Numpy

In [53]:
import numpy as np

In [54]:
# Création d'un array à partir d'une liste
v = np.array([1.0, 2.0, 3.0])
# Création d'un array de taille (n,m) initialisé à 0
z = np.zeros((3,4))
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [55]:
# Taille d'un array
print(z.shape)
print(v.shape)

(3, 4)
(3,)


In [56]:
# Opérations courantes
A = np.ones((3,3)) + np.eye(3)
print('A = ', A)
print('Av = ', np.dot(A,v))
print('3*A = ', 3*A)
print('A*v = ', A*v)
print('A + 1 = ', A+1)
print('A + v = ', A+v)
print('A^2 = ', np.square(A))

A =  [[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]
Av =  [7. 8. 9.]
3*A =  [[6. 3. 3.]
 [3. 6. 3.]
 [3. 3. 6.]]
A*v =  [[2. 2. 3.]
 [1. 4. 3.]
 [1. 2. 6.]]
A + 1 =  [[3. 2. 2.]
 [2. 3. 2.]
 [2. 2. 3.]]
A + v =  [[3. 3. 4.]
 [2. 4. 4.]
 [2. 3. 5.]]
A^2 =  [[4. 1. 1.]
 [1. 4. 1.]
 [1. 1. 4.]]


In [57]:
B = np.array([5, 2, 9, 1])

print(np.sort(B))

[1 2 5 9]


#### Compatif de performance : produit matriciel


In [58]:
import random

In [59]:
# Création d'une matrice aléatoire sous forme de liste de listes
taille = 30
A = [[random.random() for _ in range(taille)] for _ in range(taille)]

In [60]:
#print(A)

In [61]:
"""
EXERCICE - Afficher un tuple contenant les dimensions de la matrice A
"""

'\nEXERCICE - Afficher un tuple contenant les dimensions de la matrice A\n'

In [62]:
def size_list(A):
    if (type(A) != list) :
        res = []
    else :
        res = [len(A)]+size_list(A[0])
    return(res)
def size(A):
    L=size_list(A)
    return(tuple(L))

In [63]:
print(size(A))

(30, 30)


$$ (AB)_{ij} = \sum_k A_{ik} B_{kj} $$

In [64]:
"""
EXERCICE - Implémenter le produit matriciel de 2 matrices sous forme de listes de listes python
"""


'\nEXERCICE - Implémenter le produit matriciel de 2 matrices sous forme de listes de listes python\n'

In [65]:
def produit(A,B):
    (n_A,m_A)=size(A)
    (n_B,m_B)=size(B)
    assert(m_A==n_B)
    res = [[0 for _ in range(n_A)] for _ in range(m_B)]
    #print("----------------------------------------------------------------------------")
    for i in range(n_A):
        for j in range(m_B):
            #print("---------------(i,j)=",(i,j),"---------------")
            for k in range(m_A):
                #print()
                #print("i=",i)
                #print()
                #print("A[i][k]=",A[i][k])
                #print("B[k][j]=",B[k][j])
                #print("res[i][j]=",res[i][j])
                res[i][j]+=A[i][k]*B[k][j]
                #print()
                #print(np.array(res))
                #print()
    return(res)




In [66]:
# Vérification

assert(produit([[1, 2], [3, 4]], [[1, 2], [3, 4]]) == [[7, 10], [15, 22]])

In [67]:
#produit(A, A)

In [68]:
# Sortons le chronomètre
#%timeit produit(A, A)

In [69]:
# Et maintenant, avec numpy !
import numpy as np

In [70]:
A2 = np.array(A)
print(A2)

[[6.43305783e-01 5.68856687e-01 5.17326719e-02 4.89010644e-02
  7.06307326e-01 1.25461821e-01 9.07004937e-01 7.06757654e-01
  3.89891433e-01 6.99240618e-01 4.06100852e-01 9.58812057e-01
  6.57984852e-01 2.64044845e-01 2.95301161e-01 8.35792536e-01
  5.16853042e-01 7.59844578e-01 2.94857836e-01 4.93950831e-01
  5.68468608e-01 8.32214630e-01 6.41601990e-01 7.28149720e-01
  2.28920246e-01 5.21822011e-01 1.45035740e-01 2.59649627e-01
  6.74271608e-01 8.14425942e-01]
 [1.75051008e-01 5.60663113e-01 5.26038641e-01 2.30994676e-01
  9.20602668e-01 6.15480698e-01 5.42985795e-01 7.16659114e-02
  4.60725957e-01 1.53703152e-01 3.55636075e-01 1.55792326e-01
  1.71661877e-02 3.91289776e-01 8.98050430e-01 1.11994901e-01
  9.27666559e-01 2.39902250e-01 5.79566561e-01 9.29881062e-01
  9.84605296e-01 5.52412967e-01 5.04112208e-02 5.79101266e-01
  2.47252140e-02 2.66441180e-01 1.81327150e-01 5.09873252e-01
  9.61577854e-01 2.87103022e-01]
 [6.61619669e-01 1.91899911e-01 1.03146602e-01 7.88918030e-02
  5.

In [71]:
%timeit np.dot(A, A)

394 µs ± 58 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


EXERCICE - Remplissez le tableau suivant avec les durées d'exécution constatées :

(Conseil : pour la taille 3000, essayez UNIQUEMENT avec numpy)

Taille | Python | numpy
-------|--------|-------
30     | 8.29 ms| 288 µs
300    | 8.92 s | 326 µs
3000   | 2H40min| 2.75 s 

###  Pandas

In [72]:
import pandas as pd

In [73]:
df_exemple = pd.DataFrame({"ESN": ["E420912", "E420913", "E420914"], "panne": [False, False, True]})
df_exemple

ESN  panne
0  E420912  False
1  E420913  False
2  E420914   True

#### Lecture et prétraitement de données


In [74]:
!git clone https://github.com/MadaneA/MACS3-Statistiques-Descriptives-TDs.git

fatal: destination path 'MACS3-Statistiques-Descriptives-TDs' already exists and is not an empty directory.


In [75]:
import os
os.chdir('MACS3-Statistiques-Descriptives-TDs')

In [77]:
# Chargement d'un fichier CSV ou Excel
df = pd.read_csv("./data/Vol010.csv")
# Affichage des 5 premières lignes
df.head()

t EGT_SEL FLIGHT_MOD FMV_SEL HPTC_SEL LPTC_SEL  \
0                  datenum   deg_C          _       _        %        %   
1  15/09/2011 14:25:58.125     NaN        NaN     NaN      NaN      NaN   
2  15/09/2011 14:25:58.375     NaN        NaN     NaN      NaN      NaN   
3  15/09/2011 14:25:58.625     NaN        NaN     NaN      NaN      NaN   
4  15/09/2011 14:25:58.875     NaN        NaN     NaN      NaN      NaN   

  N1_SEL N2_ACTSEL OIL_P OIL_TEMP  ... T25_SEL T3_SEL VBV_SEL VIB_CN1 VIB_CN2  \
0      %     %_RPM   psi        _  ...       _      _     DEG       _       _   
1    NaN         0   NaN      NaN  ...     NaN    NaN     NaN     NaN     NaN   
2    NaN         0   NaN      NaN  ...     NaN    NaN     NaN     NaN     NaN   
3    NaN         0   NaN      NaN  ...     NaN    NaN     NaN     NaN     NaN   
4    NaN         0   NaN      NaN  ...     NaN    NaN     NaN     NaN     NaN   

  VIB_TN1 VIB_TN2 VSV_SEL  WFM_SEL    XM  
0       _       _     DEG     lb/h  mach  
1     NaN     NaN     NaN      NaN   NaN  
2     NaN     NaN     NaN      NaN   NaN  
3     NaN     NaN     NaN      NaN   NaN  
4     NaN     NaN     NaN  7679.98  0.15  

[5 rows x 26 columns]

In [85]:
"""
EXERCICE - Dimensions d'un DataFrame
Affichez le nombre de colonnes et de ligne du DataFrame (indice : beaucoup de méthodes sont communes entre numpy et pandas)
"""
print('Nombre de colonnes :', df.shape[1])
print('Nombre de lignes :', df.shape[0])

Nombre de colonnes : 26
Nombre de lignes : 22945


In [86]:
df.size, len(df)

(596570, 22945)

In [87]:
df.columns

Index(['t', 'EGT_SEL', 'FLIGHT_MOD', 'FMV_SEL', 'HPTC_SEL', 'LPTC_SEL',
       'N1_SEL', 'N2_ACTSEL', 'OIL_P', 'OIL_TEMP', 'PS3_SEL', 'PT2_SEL',
       'P0_SEL', 'TAT', 'TBV_SEL', 'TRA_SEL', 'T25_SEL', 'T3_SEL', 'VBV_SEL',
       'VIB_CN1', 'VIB_CN2', 'VIB_TN1', 'VIB_TN2', 'VSV_SEL', 'WFM_SEL', 'XM'],
      dtype='object')

Les colonnes des DF sont typées, à la manière d'une base de données relationnelle, contrairement aux variables python classiques. Les types des colonnes sont accessibles via df.dtypes. Les principaux types sont les numériques (int32, int64, float etc.

In [102]:
df.loc[10:15, ['EGT_SEL', 'FLIGHT_MOD']]

EGT_SEL FLIGHT_MOD
10    0.00234327        NaN
11  1.08032e-007        NaN
12  3.12514e-012        NaN
13             0        NaN
14       72.0006        NaN
15       215.996        NaN

In [106]:
"""
EXERCICE - Extraction et suppression des unités
On remarque que la 1ère ligne ne contient pas de données mais les unités de chaque colonne.
Pour la suite des traitements, il faut supprimer cette ligne. On souhaite toutefois garder l'information des unités de chaque colonne.
1. Récupérez les unités et stockez les dans une structure adaptée.
2. Supprimez cette ligne du DataFrame en utilisant la méthode "drop"
"""
units=df.loc[0]
df.drop(0,inplace=True)



In [107]:
print(units)
df.head()

t             datenum
EGT_SEL         deg_C
FLIGHT_MOD          _
FMV_SEL             _
HPTC_SEL            %
LPTC_SEL            %
N1_SEL              %
N2_ACTSEL       %_RPM
OIL_P             psi
OIL_TEMP            _
PS3_SEL           psi
PT2_SEL            mb
P0_SEL            psi
TAT             deg_C
TBV_SEL             %
TRA_SEL           DEG
T25_SEL             _
T3_SEL              _
VBV_SEL           DEG
VIB_CN1             _
VIB_CN2             _
VIB_TN1             _
VIB_TN2             _
VSV_SEL           DEG
WFM_SEL          lb/h
XM               mach
Name: 0, dtype: object


t EGT_SEL FLIGHT_MOD FMV_SEL HPTC_SEL LPTC_SEL  \
1  15/09/2011 14:25:58.125     NaN        NaN     NaN      NaN      NaN   
2  15/09/2011 14:25:58.375     NaN        NaN     NaN      NaN      NaN   
3  15/09/2011 14:25:58.625     NaN        NaN     NaN      NaN      NaN   
4  15/09/2011 14:25:58.875     NaN        NaN     NaN      NaN      NaN   
5  15/09/2011 14:25:59.125     NaN        NaN     NaN      NaN      NaN   

  N1_SEL N2_ACTSEL    OIL_P OIL_TEMP  ... T25_SEL T3_SEL VBV_SEL VIB_CN1  \
1    NaN         0      NaN      NaN  ...     NaN    NaN     NaN     NaN   
2    NaN         0      NaN      NaN  ...     NaN    NaN     NaN     NaN   
3    NaN         0      NaN      NaN  ...     NaN    NaN     NaN     NaN   
4    NaN         0      NaN      NaN  ...     NaN    NaN     NaN     NaN   
5      0         0  647.998      NaN  ...     NaN    NaN       0       0   

  VIB_CN2 VIB_TN1 VIB_TN2 VSV_SEL  WFM_SEL    XM  
1     NaN     NaN     NaN     NaN      NaN   NaN  
2     NaN     NaN     NaN     NaN      NaN   NaN  
3     NaN     NaN     NaN     NaN      NaN   NaN  
4     NaN     NaN     NaN     NaN  7679.98  0.15  
5       0       0       0       0  4607.86  0.15  

[5 rows x 26 columns]

On remarque que toutes les colonnes ont été reconnues comme de type object, c'est-à-dire des chaînes de caractères, alors que ce sont des valeurs numériques. Cela est dû à la première ligne contenant les unités. Il faut donc convertir les colonnes en numérique. La colonne 't', quant à elle, doit être convertie en type datetime.

In [109]:
df['t'] = pd.to_datetime(df['t'])
df[df.columns[1:]] = df[df.columns[1:]].apply(pd.to_numeric)

In [110]:
df.dtypes

t             datetime64[ns]
EGT_SEL              float64
FLIGHT_MOD           float64
FMV_SEL              float64
HPTC_SEL             float64
LPTC_SEL             float64
N1_SEL               float64
N2_ACTSEL            float64
OIL_P                float64
OIL_TEMP             float64
PS3_SEL              float64
PT2_SEL              float64
P0_SEL               float64
TAT                  float64
TBV_SEL              float64
TRA_SEL              float64
T25_SEL              float64
T3_SEL               float64
VBV_SEL              float64
VIB_CN1              float64
VIB_CN2              float64
VIB_TN1              float64
VIB_TN2              float64
VSV_SEL              float64
WFM_SEL              float64
XM                   float64
dtype: object

In [158]:
"""
Exercice - Index temporel
Comme nos données sont une série temporelle multivariée, on souhaite utiliser un index temporel.
1. Créez une copie de df, appelée df2, à l'aide de la méthode du même nom.
2. Affectez la colonne du temps ('t') en tant qu'indice du DataFrame.
3. Supprimez la colonne 't' du DF résultant.
"""
df2=df.copy()
df2.index=df2.iloc[:,0]
df2.drop('t',axis='columns',inplace=True)
df2

EGT_SEL  FLIGHT_MOD  FMV_SEL  HPTC_SEL  LPTC_SEL  \
t                                                                           
2011-09-15 14:25:58.125      NaN         NaN      NaN       NaN       NaN   
2011-09-15 14:25:58.375      NaN         NaN      NaN       NaN       NaN   
2011-09-15 14:25:58.625      NaN         NaN      NaN       NaN       NaN   
2011-09-15 14:25:58.875      NaN         NaN      NaN       NaN       NaN   
2011-09-15 14:25:59.125      NaN         NaN      NaN       NaN       NaN   
...                          ...         ...      ...       ...       ...   
2011-09-15 16:01:32.875      NaN         NaN      NaN       NaN       NaN   
2011-09-15 16:01:33.125      NaN         NaN      NaN       NaN       NaN   
2011-09-15 16:01:33.375      NaN         NaN      NaN       NaN       NaN   
2011-09-15 16:01:33.625      NaN         NaN      NaN       NaN       NaN   
2011-09-15 16:01:33.875      NaN         NaN      NaN       NaN       NaN   

                         N1_SEL  N2_ACTSEL    OIL_P  OIL_TEMP  PS3_SEL  ...  \
t                                                                       ...   
2011-09-15 14:25:58.125     NaN        0.0      NaN       NaN      NaN  ...   
2011-09-15 14:25:58.375     NaN        0.0      NaN       NaN      NaN  ...   
2011-09-15 14:25:58.625     NaN        0.0      NaN       NaN      NaN  ...   
2011-09-15 14:25:58.875     NaN        0.0      NaN       NaN      NaN  ...   
2011-09-15 14:25:59.125     0.0        0.0  647.998       NaN  575.982  ...   
...                         ...        ...      ...       ...      ...  ...   
2011-09-15 16:01:32.875     NaN        NaN      NaN       NaN      NaN  ...   
2011-09-15 16:01:33.125     NaN        NaN      NaN       NaN      NaN  ...   
2011-09-15 16:01:33.375     NaN        NaN      NaN       NaN      NaN  ...   
2011-09-15 16:01:33.625     NaN        NaN      NaN       NaN      NaN  ...   
2011-09-15 16:01:33.875     NaN        NaN      NaN       NaN      NaN  ...   

                         T25_SEL  T3_SEL  VBV_SEL  VIB_CN1  VIB_CN2  VIB_TN1  \
t                                                                              
2011-09-15 14:25:58.125      NaN     NaN      NaN      NaN      NaN      NaN   
2011-09-15 14:25:58.375      NaN     NaN      NaN      NaN      NaN      NaN   
2011-09-15 14:25:58.625      NaN     NaN      NaN      NaN      NaN      NaN   
2011-09-15 14:25:58.875      NaN     NaN      NaN      NaN      NaN      NaN   
2011-09-15 14:25:59.125      NaN     NaN      0.0      0.0      0.0      0.0   
...                          ...     ...      ...      ...      ...      ...   
2011-09-15 16:01:32.875      NaN     NaN      NaN      NaN      NaN      NaN   
2011-09-15 16:01:33.125      NaN     NaN      NaN      NaN      NaN      NaN   
2011-09-15 16:01:33.375      NaN     NaN      NaN      NaN      NaN      NaN   
2011-09-15 16:01:33.625      NaN     NaN      NaN      NaN      NaN      NaN   
2011-09-15 16:01:33.875      NaN     NaN      NaN      NaN      NaN      NaN   

                         VIB_TN2  VSV_SEL  WFM_SEL    XM  
t                                                         
2011-09-15 14:25:58.125      NaN      NaN      NaN   NaN  
2011-09-15 14:25:58.375      NaN      NaN      NaN   NaN  
2011-09-15 14:25:58.625      NaN      NaN      NaN   NaN  
2011-09-15 14:25:58.875      NaN      NaN  7679.98  0.15  
2011-09-15 14:25:59.125      0.0      0.0  4607.86  0.15  
...                          ...      ...      ...   ...  
2011-09-15 16:01:32.875      NaN      NaN      NaN   NaN  
2011-09-15 16:01:33.125      NaN      NaN      NaN   NaN  
2011-09-15 16:01:33.375      NaN      NaN      NaN   NaN  
2011-09-15 16:01:33.625      NaN      NaN      NaN   NaN  
2011-09-15 16:01:33.875      NaN      NaN      NaN   NaN  

[22944 rows x 25 columns]

On constate que pandas a automatiquement reconnu un DatetimeIndex, adapté pour des manipulations de séries temporelles (moyennes glissantes, etc) !

### Valeurs manquantes

**NaN = Not a Number**

Les valeurs NaN doivent être éliminées ou imputées (i.e. remplacées par une certaine valeur) avant la suite des traitements. Ce choix dépend du cas d'usage. Dans un premier temps, nous allons apprendre à :

* trouver les données manquantes (méthode `isna`)
* éliminer les données manquantes d'un DataFrame (méthode `dropna`)
* les remplacer par une constante (méthode (`fillna`)

In [213]:
"""
EXERCICE - La méthode isna
1. Testez la méthode isna sur le DataFrame df2, puis sur une colonne ou une ligne. Que renvoie-t-elle ?
2. En appliquant les méthodes any(axis=...), mean() et max()/idxmax() sur les résultats de isna(), répondez aux questions suivantes :
    2.1 Quelles colonnes contiennent des valeurs manquantes, lesquelles n'en contiennent pas ?
    2.2 Quel est le pourcentage de valeurs manquantes dans le DF (a) par colonne (b) globalement ? Quelle variable contient le plus de NaN ?
    2.3 Quel est le pourcentage d'indices du DF pour lesquels toutes les variables sont présentes ?
"""
#print(df2.isna())
#print(df2.iloc[0].isna())
#print(df2.iloc[:,0].isna())
print('Question 2.1')
nrow,ncol=df2.shape
res=[]
for j in range(ncol):
    if sum(df2.iloc[:,j].isna()) == 0 :
        res.append(df2.columns[j])
print('Les colonnes qui ne contiennent pas de NaN sont :',res)

print('Question 2.2')
print('a)')
S=0
for j in range(ncol):
    S+=sum(df2.iloc[:,j].isna())
print('il y a ',(1-S/df2.size)*100,'%  de NaN dans le dataframe ')

print('b)')
M=0
i_M=0
L=[]
N=df2.shape[0]

for j in range(ncol):
    x=(1-(sum(df2.iloc[:,j].isna())/N))*100
    if M>x:
        M=x
        i_M=j
    L.append(x)
print('Les pourcentages de NaN dans chacune des colonnes est :')
print(L)

print('La catégorie qui a le plus grand nombre de NaN est :',df.columns[i_M+1])
print('Question 2.3')

res=0
for i in range(nrow):
    if sum(df2.iloc[i,:].isna()) != 0 :
        res+=1
print('il y a',res/len(df2.index)*100,'%  lignes qui ne contiennent pas de NaN')



Question 2.1
Les colonnes qui ne contiennent pas de NaN sont : []
Question 2.2
a)
il y a  99.65306834030685 %  de NaN dans le dataframe 
b)
Les pourcentages de NaN dans chacune des colonnes est :
[99.65132496513249, 99.55543933054393, 99.55543933054393, 99.57723152022315, 99.5423640167364, 99.581589958159, 99.74721059972106, 99.6208158995816, 99.61645746164575, 99.69926778242679, 99.62953277545327, 99.62953277545327, 99.69926778242679, 99.70362622036262, 99.69926778242679, 99.52928870292888, 99.52928870292888, 99.70798465829847, 99.70798465829847, 99.71670153417016, 99.71670153417016, 99.71670153417016, 99.72541841004184, 99.72977684797767, 99.73849372384937]
La catégorie qui a le plus grand nombre de NaN est : EGT_SEL
Question 2.3
il y a 0.5186541143654114 %  lignes qui ne contiennent pas de NaN


In [ ]:
"""
EXERCICE - La méthode dropna
La méthode dropna permet d'éliminer les valeurs manquantes (NaN). Lisez d'abord sa documentation.
1. À quoi correspondent les arguments "axis" et "how" ?
2. Éliminez toutes les lignes contenant uniquement des valeurs manquantes.
3. Éliminez toutes les lignes contenant au moins une valeur manquante. Combien y a-t-il de lignes de différence ?
4. Éliminez toutes les colonnes contenant au moins une valeur manquante.
"""


In [ ]:
df2.dropna()
print('Question 1')
print("l'argument axis correspond a l'axe du dataframe (axis = 0 ou 'index' pour les index[par défaut] et 1 ou 'columns' pour les colonnes) que l on doit enlever pour une valeur de type NaN ")
print("l'argument how correspond au critère que l'on choisi pour enlever les colonnes ou ligne choisie : soit 'any' pour enlever la colonne ou ligne si elle contient au moins un NaN [par défaut] soit 'all' pour enlever la colonne ou ligne si elle ne contient que des NaN  ")
print('Question 2')
n_row=df2.shape[0]
df2.dropna(how='all',inplace=True)
diff1=n_row-df2.shape[0]
print(diff1)
print('Question 3')
df2.dropna(inplace=True)
diff2=n_row-df2.shape[0]
print("il y a ",diff2-diff1," lignes de différences")
print('Question 4')
df2.dropna(axis=1,inplace=True)
df2.head()

In [286]:
"""
EXERCICE - La méthode fillna
La méthode dropna permet d'imputer les valeurs manquantes (NaN). Lisez d'abord sa documentation.
1. Quelles sont les différentes stratégies de remplissage des valeurs manquantes ?
2. Imputez les valeurs manquantes de la colonne age du DF donné en exemple par :
    - 0
    - la dernière valeur précédente/suivante valide
    - la moyenne
    - la valeur la plus courante (mode)
3. Quel est le meilleur choix dans ce cas ? Et pour le cas d'une variable temporelle, par exemple la température 'EGT_SEL' de notre jeu de données ?
"""
exemple = pd.DataFrame({'nom': ['Alice', 'Bob', 'Charlie', 'David'], 'age': [24, np.nan, 99, 24]})

print('Question 1')
print("Les NaN peuvent etre remplis avec des scalaires dictionnaires séries ou dataframe et selon différentes méthodes : ")
print('Question 2')
exemple.fillna(0)
exemple.fillna(method='ffill')
exemple.fillna(method='bfill')
mean=sum(exemple.iloc[:,1].dropna())/len(exemple.iloc[:,1].dropna())
exemple.fillna(mean)
mod=exemple.iloc[:,1].mode()
print(mod)
exemple.fillna(mod[0])
print('Question 3')
print("le meilleur choix ici serait de remplacer par la moyenne pour ne pas impacter trop les statitiques") 
print("le meilleur choix pour une variable temporelle serait de remplacer par la moyenne du précédent et du suivant pour ne pas impacter trop les graphiques") 


Question 1
Les NaN peuvent etre remplis avec des scalaires dictionnaires séries ou dataframe et selon différentes méthodes : 
Question 2
0    24.0
dtype: float64
Question 1


nom   age
0    Alice  24.0
1      Bob  24.0
2  Charlie  99.0
3    David  24.0

## Git

Créer un compte GitHub : https://github.com/

Créer un nouveau repository :
1. Sélectionner "Nouveau dépôt" dans le menu déroulant avec le signe +. 
2. Saisisser un nom pour votre dépôt (par exemple, "TDs statistiques descriptives") 
3. Cliquer sur "Créer un dépôt". Ne vous souciez pas des autres options.



Télécharger Git Bash : https://git-scm.com/downloads

Sur Git Bash, positionnez-vous dans le répertoire où votre projet figure.

Ensuite

> git init

> git remote add origin https://github.com/********

> git add .

> git commit -m "Ajout du TD1"

> git push origin master

C'est tout ! Vous avez créé votre repo GitHub ! 